stages:
  - build

variables:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  GIT_SUBMODULE_STRATEGY: normal

internal:
  tags:
    - ios
  stage: build
  only:
    - master
  except:
    - tags
  script:
    - sh ~/ios-prepare-build.sh $CI_PROJECT_DIR/..
    - fastlane internalhockeyapp
  environment:
    name: internal

beta_testflight:
  tags:
    - ios
  stage: build
  only:
    - beta
  except:
    - tags
  script:
    - sh ~/ios-prepare-build.sh $CI_PROJECT_DIR/..
    - fastlane testflight_llc
  environment:
    name: testflight_llc
